//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_DB_Projects.model.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Area()
        {
            this.Area_group = new HashSet<Area_group>();
            this.Area_group1 = new HashSet<Area_group>();
            this.Objects = new HashSet<Objects>();
            this.Object_Area = new HashSet<Object_Area>();
            this.Object_Area1 = new HashSet<Object_Area>();
        }
    
        public int Area_id { get; set; }
        public Nullable<int> Area_id_access { get; set; }
        public string Area_CRM_code { get; set; }
        public int Area_type_id { get; set; }
        public Nullable<int> Area_access_type_id { get; set; }
        public Nullable<float> Area_lenght { get; set; }
        public Nullable<float> Area_width { get; set; }
        public Nullable<int> Area_area { get; set; }
        public bool Is_realty { get; set; }
        public bool Is_living { get; set; }
        public bool Is_wet { get; set; }
        public bool Is_open { get; set; }
        public bool Is_heated { get; set; }
    
        public virtual Area_type Area_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area_group> Area_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area_group> Area_group1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Objects> Objects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object_Area> Object_Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object_Area> Object_Area1 { get; set; }
    }
}
