//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_DB_Projects.model.db
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDMEntities : DbContext
    {
        public MDMEntities(DbConnection dbCon)
            : base(dbCon, true)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Area_group> Area_group { get; set; }
        public virtual DbSet<Area_type> Area_type { get; set; }
        public virtual DbSet<Building_part> Building_part { get; set; }
        public virtual DbSet<Construction_type> Construction_type { get; set; }
        public virtual DbSet<Floor_type> Floor_type { get; set; }
        public virtual DbSet<Object_Area> Object_Area { get; set; }
        public virtual DbSet<Object_Area_Item> Object_Area_Item { get; set; }
        public virtual DbSet<Object_Item> Object_Item { get; set; }
        public virtual DbSet<Object_type> Object_type { get; set; }
        public virtual DbSet<Objects> Objects { get; set; }
        public virtual DbSet<Project_type> Project_type { get; set; }
        public virtual DbSet<Object_cascade> Object_cascade { get; set; }
    }
}
