//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_DB_Projects.model.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object_Item()
        {
            this.Object_Area_Item = new HashSet<Object_Area_Item>();
        }
    
        public int Object_Item_id { get; set; }
        public Nullable<int> Object_id { get; set; }
        public Nullable<int> Item_construction_id { get; set; }
        public Nullable<int> Item_construction_colour_id { get; set; }
        public Nullable<int> Object_Item_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object_Area_Item> Object_Area_Item { get; set; }
        public virtual Objects Objects { get; set; }
    }
}
