//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_DB_Projects.model.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_cascade
    {
        public int Object_id { get; set; }
        public string Object { get; set; }
        public string Object_type { get; set; }
        public Nullable<int> Object_id_parent { get; set; }
    }
}
