//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_DB_Projects.model.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objects()
        {
            this.Object_Area = new HashSet<Object_Area>();
            this.Object_Item = new HashSet<Object_Item>();
            this.Objects1 = new HashSet<Objects>();
        }
    
        public int Object_id { get; set; }
        public Nullable<int> Object_id_access { get; set; }
        public Nullable<int> Object_id_parent { get; set; }
        public Nullable<int> Object_type_id { get; set; }
        public string Cadaster_number { get; set; }
        public string Object_name { get; set; }
        public Nullable<int> Object_number { get; set; }
        public string Object_number_add { get; set; }
        public Nullable<int> Project_type_id { get; set; }
        public Nullable<int> Usage_mos_id { get; set; }
        public Nullable<int> Address_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Building_part_id { get; set; }
        public Nullable<int> Construction_type_id { get; set; }
        public Nullable<short> Floors { get; set; }
        public Nullable<int> Froor_type_id { get; set; }
        public Nullable<bool> Is_floor { get; set; }
        public Nullable<bool> Is_technical { get; set; }
        public Nullable<int> Area_id { get; set; }
        public Nullable<bool> Is_building { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Building_part Building_part { get; set; }
        public virtual Construction_type Construction_type { get; set; }
        public virtual Floor_type Floor_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object_Area> Object_Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object_Item> Object_Item { get; set; }
        public virtual Object_type Object_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Objects> Objects1 { get; set; }
        public virtual Objects Objects2 { get; set; }
        public virtual Project_type Project_type { get; set; }
    }
}
