//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_DB_Projects.model.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object_Area()
        {
            this.Object_Area_Item = new HashSet<Object_Area_Item>();
        }
    
        public int Object_Area_id { get; set; }
        public Nullable<int> Object_Area_ext_id { get; set; }
        public Nullable<int> Area_int_id { get; set; }
        public Nullable<int> Area_id_no_parent { get; set; }
        public Nullable<int> Object_Area_ext_number { get; set; }
        public Nullable<int> Area_int_number { get; set; }
        public string Object_Area_ext_Area_int_number { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Area Area1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object_Area_Item> Object_Area_Item { get; set; }
        public virtual Objects Objects { get; set; }
    }
}
