//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Sections
    {
        public int ID_Section { get; set; }
        public int CountModules { get; set; }
        public string Type { get; set; }
        public string Levels { get; set; }
        public string Include { get; set; }
    }
}
