//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_DB_Projects.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/model.db.ModelDB.csdl|res://*/model.db.ModelDB.ssdl|res://*/model.db.ModelDB.msl;provider=System.Data.SqlClient;provider connection string=""data source=cad01pik;initial catalog=MDM;persist security info=True;user id=Vildar;password=28Vildar;MultipleActiveResultSets=True;App=EntityFramework""")]
        public string MdmCon {
            get {
                return ((string)(this["MdmCon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/model.ins.ModelIns.csdl|res://*/model.ins.ModelIns.ssdl|res://*/model.ins.ModelIns.msl;provider=System.Data.SqlClient;provider connection string=""data source=cad01pik;initial catalog=MDM;persist security info=True;user id=Vildar;password=28Vildar;MultipleActiveResultSets=True;App=EntityFramework""")]
        public string InsCon {
            get {
                return ((string)(this["InsCon"]));
            }
        }
    }
}
