//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_DB_Projects.model.ins
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insolation_Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insolation_Object()
        {
            this.Insolation_Object_Point = new HashSet<Insolation_Object_Point>();
        }
    
        public int Insolation_Object_id { get; set; }
        public int Object_id { get; set; }
        public Nullable<int> Insolation_version_id { get; set; }
    
        public virtual Insolation_version Insolation_version { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insolation_Object_Point> Insolation_Object_Point { get; set; }
    }
}
