//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_DB_Projects.model.ins
{
    using System;
    using System.Data.Entity;
    using System.Data.Common;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsEntities : DbContext
    {
        public InsEntities(DbConnection dbCon)
            : base(dbCon, true)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Insolation_Object> Insolation_Object { get; set; }
        public virtual DbSet<Insolation_type> Insolation_type { get; set; }
        public virtual DbSet<Insolation_version> Insolation_version { get; set; }
        public virtual DbSet<Insolation_Object_Point> Insolation_Object_Point { get; set; }
    }
}
